#!/bin/bash

# WealthWise Vercel Deployment Quick Setup
# This script provides step-by-step instructions for deploying to Vercel

echo "=========================================="
echo "WealthWise Vercel Deployment Setup"
echo "=========================================="
echo ""

echo "Step 1: Install Vercel CLI"
echo "Run: npm i -g vercel"
echo ""

echo "Step 2: Backend Deployment"
echo "2a. Navigate to server directory:"
echo "    cd server"
echo ""
echo "2b. Login to Vercel:"
echo "    vercel login"
echo ""
echo "2c. Deploy backend:"
echo "    vercel --prod"
echo ""
echo "2d. During deployment, configure:"
echo "    - Project name: wealthwise-backend (or your preference)"
echo "    - Framework: Other"
echo "    - Root directory: ./ (if deploying from server folder)"
echo ""
echo "Note your backend URL (e.g., https://wealthwise-backend.vercel.app)"
echo ""

echo "Step 3: Set Backend Environment Variables on Vercel"
echo "Go to: https://vercel.com/dashboard"
echo "Select your backend project → Settings → Environment Variables"
echo ""
echo "Add these variables:"
echo "  NODE_ENV = production"
echo "  MONGODB_URI = <your-mongodb-connection-string>"
echo "  JWT_SECRET = <generate-a-strong-random-secret>"
echo "  JWT_EXPIRES_IN = 7d"
echo "  CLIENT_URL = https://your-frontend-vercel-url.vercel.app"
echo ""

echo "Step 4: Frontend Deployment"
echo "4a. Go back to client directory:"
echo "    cd ../client"
echo ""
echo "4b. Deploy frontend:"
echo "    vercel --prod"
echo ""
echo "4c. During deployment, configure:"
echo "    - Project name: wealthwise-frontend (or your preference)"
echo "    - Framework: Vite"
echo ""
echo "Note your frontend URL (e.g., https://wealthwise-frontend.vercel.app)"
echo ""

echo "Step 5: Set Frontend Environment Variables on Vercel"
echo "Go to: https://vercel.com/dashboard"
echo "Select your frontend project → Settings → Environment Variables"
echo ""
echo "Add this variable:"
echo "  VITE_API_BASE_URL = https://your-backend-vercel-url.vercel.app/api"
echo ""
echo "(Replace with your actual backend URL from Step 3)"
echo ""

echo "Step 6: Update Backend CLIENT_URL"
echo "Go back to backend project settings"
echo "Update CLIENT_URL to your frontend Vercel URL"
echo ""

echo "Step 7: Redeploy Both"
echo "Backend: vercel --prod (from server folder)"
echo "Frontend: vercel --prod (from client folder)"
echo ""

echo "Step 8: Test"
echo "Visit: https://your-frontend-vercel-url.vercel.app"
echo "Check browser console for any errors"
echo "Test API: https://your-backend-vercel-url.vercel.app/api/health"
echo ""

echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
